### ISSUE TITLE
Buzz reported issue

### ISSUE THREAD

**Issue by slejnej** [nixilla/api-logger-bundle#5]
Hi,

in order to get the data after logCall was made we are missing code to reset the pointer of contents, else in Symfony 4+ data is always empty. Reported in [this issue](https://github.com/8p/EightPointsGuzzleBundle/issues/48)

In ApiLoggerMiddleware.php on line 56 we could just do..
`
/** need to rewind the contents so it can be retrieved later!!! */
$response->getBody()->rewind();
`

**Comment by nixilla** [comment]
TRISTO KOSMATYH!!!! Send me a pull request, please.

**Comment by nixilla** [comment]
@slejnej fixed - release created!

Thank you!!
